name: "🐛 ​​Bug Report"
description: Report an issue or possible bug.
labels: [bug]
assignees: []
body:
  - type: textarea
    id: bug
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is and the steps to reproduce.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Output from the console (if any)
      description: Please provide any relevant log output.
  - type: checkboxes
    id: participation
    attributes:
      label: Participation
      options:
        - label:  I am willing to submit a pull request for this issue.
          required: false